schema_version = "1.0.0"

id = "M2V"
version = "1.1.0"
name = "MIDI To Visuals"
tagline = "With MIDI file as input create somes 3D animations in blender"
maintainer = "Patochun - Patrick M. <ptkmgr@gmail.com>"
type = "add-on"
website = "https://github.com/Patochun"
tags = ["Animation"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]